error_on_line_overflow = true
max_width = 120
chain_width = 120
single_line_if_else_max_width = 120
single_line_let_else_max_width = 120
struct_lit_width = 80
fn_single_line = true
newline_style = "Unix"
version = "Two"